name: GitHub Pull Request Action
on: push
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: creates PR
      uses: repo-sync/pull-request@v2.4.1
      with:
        # Branch name to sync to in this repo, default is master
        destination_branch: master
        # GitHub token secret
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_reviewer: VenkateshRavula
